version: '3.1'

services:
  postgis_db:
    image: postgis/postgis
    container_name: postgis_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  django_locs:
    build: .
    container_name: django_locs
    working_dir: /app
    command: ["./wait.sh", "postgis_db", "python", "manage.py", "runserver", "0:5001"]
    ports:
      - 5001:5001
    volumes:
      - .:/code
    depends_on:
      - postgis_db

volumes:
  .:
  postgres_data:
